# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - cyclop          # Checks if the cyclic complexity of a function is acceptable
    - dogsled         # Checks assignments with too many blank identifiers (e.g. x, , , _, := f())
    - durationcheck
    - dupl            # Detects code duplication
    - errcheck
    - exportloopref
    - forcetypeassert 
    - funlen          # Detects long functions
    - gocritic        # Provides diagnostics that check for bugs, performance and style issues
    - godot
    - gofmt           # Checks whether code was gofmt-ed
    - gosec           # Inspects source code for security problems
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell        # Finds commonly misspelled English words in comments
    - nestif          # Reports deeply nested if statements
    - nilerr          # Finds the code that returns nil even if it checks that the error is not nil
    - predeclared
    - staticcheck
    - tenv
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Reports unused function parameters
    - unused
    - whitespace      # Detects leading and trailing whitespace

linters-settings:
  funlen:
    lines: 100
    statements: 50    
